steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
      - "--build-arg"
      - "ENVIRONMENT=prod"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: "Push"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy"
    args:
      - "run"
      - "deploy"
      - "zip-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
      - "--platform"
      - "gke"
      - "--cluster"
      - "prv-qa-internal"
      - "--cluster-location"
      - "us-east1-b"
      - "--namespace"
      - "prv-sistemasinternos"
      - "--port"
      - "4000"
